services:
  db:
    image: postgres:18-alpine
    container_name: db-surat
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs-sistem-surat-dev
    volumes:
      - .:/app                  # hot reload — sync source code
      - /app/node_modules       # isolasi node_modules container
      - /app/.next              # isolasi .next cache container
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: