name: Review Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  integration-check:
    name: Strict Integration Check
    runs-on: ubuntu-latest
    
    # Memasang env di sini agar otomatis tersedia untuk SEMUA langkah di bawahnya
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Linter
        run: npm run lint

      - name: TypeScript Check
        run: npx tsc --noEmit

      - name: Build Application
        run: npm run build