name: Staging Deployment

on:
  push:
    branches:
      - staging

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/sistem-surat:staging
            
    deploy:
        name: Pembaruan Container di VPS
        needs: build-and-push
        runs-on: ubuntu-latest
        steps:
            - name: Eksekusi Remote SSH Via Tabby key
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.VPS_SSH_KEY }}
                script: |
                    cd /var/www/docker-staging
                    DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} docker compose -f docker-compose.staging.yml pull
                    DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} docker compose -f docker-compose.staging.yml up -d

                    sleep 5
                    
                    docker exec sistem_surat_staging npx prisma migrate deploy